/* Generated By:JJTree&JavaCC: Do not edit this line. SalsaParserConstants.java */
package salsa_lite.compiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SalsaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 10;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 11;
  /** RegularExpression Id. */
  int ACK = 13;
  /** RegularExpression Id. */
  int AT = 14;
  /** RegularExpression Id. */
  int BEHAVIOR = 15;
  /** RegularExpression Id. */
  int BOOLEAN = 16;
  /** RegularExpression Id. */
  int BREAK = 17;
  /** RegularExpression Id. */
  int BYTE = 18;
  /** RegularExpression Id. */
  int CASE = 19;
  /** RegularExpression Id. */
  int CHAR = 20;
  /** RegularExpression Id. */
  int CONST = 21;
  /** RegularExpression Id. */
  int _DEFAULT = 22;
  /** RegularExpression Id. */
  int DELAY = 23;
  /** RegularExpression Id. */
  int DOUBLE = 24;
  /** RegularExpression Id. */
  int ENUM = 25;
  /** RegularExpression Id. */
  int ELSE = 26;
  /** RegularExpression Id. */
  int ENDIF = 27;
  /** RegularExpression Id. */
  int EXTENDS = 28;
  /** RegularExpression Id. */
  int FALSE = 29;
  /** RegularExpression Id. */
  int FLOAT = 30;
  /** RegularExpression Id. */
  int FOR = 31;
  /** RegularExpression Id. */
  int IF = 32;
  /** RegularExpression Id. */
  int IMPLEMENTS = 33;
  /** RegularExpression Id. */
  int IMPORT = 34;
  /** RegularExpression Id. */
  int INSTANCEOF = 35;
  /** RegularExpression Id. */
  int INT = 36;
  /** RegularExpression Id. */
  int INTERFACE = 37;
  /** RegularExpression Id. */
  int LATER = 38;
  /** RegularExpression Id. */
  int LONG = 39;
  /** RegularExpression Id. */
  int LOOP = 40;
  /** RegularExpression Id. */
  int MODULE = 41;
  /** RegularExpression Id. */
  int NEW = 42;
  /** RegularExpression Id. */
  int NULL = 43;
  /** RegularExpression Id. */
  int OBJECT = 44;
  /** RegularExpression Id. */
  int PASS = 45;
  /** RegularExpression Id. */
  int PARENT = 46;
  /** RegularExpression Id. */
  int PUBLIC = 47;
  /** RegularExpression Id. */
  int REFERENCE = 48;
  /** RegularExpression Id. */
  int SELF = 49;
  /** RegularExpression Id. */
  int SHORT = 50;
  /** RegularExpression Id. */
  int SUPER = 51;
  /** RegularExpression Id. */
  int SWITCH = 52;
  /** RegularExpression Id. */
  int _TOKEN = 53;
  /** RegularExpression Id. */
  int TRUE = 54;
  /** RegularExpression Id. */
  int WAITFOR = 55;
  /** RegularExpression Id. */
  int WHILE = 56;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 57;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 58;
  /** RegularExpression Id. */
  int HEX_LITERAL = 59;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 60;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 61;
  /** RegularExpression Id. */
  int EXPONENT = 62;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 63;
  /** RegularExpression Id. */
  int STRING_LITERAL = 64;
  /** RegularExpression Id. */
  int IDENTIFIER = 65;
  /** RegularExpression Id. */
  int LETTER = 66;
  /** RegularExpression Id. */
  int DIGIT = 67;
  /** RegularExpression Id. */
  int LPAREN = 68;
  /** RegularExpression Id. */
  int RPAREN = 69;
  /** RegularExpression Id. */
  int LBRACE = 70;
  /** RegularExpression Id. */
  int RBRACE = 71;
  /** RegularExpression Id. */
  int LBRACKET = 72;
  /** RegularExpression Id. */
  int RBRACKET = 73;
  /** RegularExpression Id. */
  int SEMICOLON = 74;
  /** RegularExpression Id. */
  int COMMA = 75;
  /** RegularExpression Id. */
  int DOT = 76;
  /** RegularExpression Id. */
  int MSG = 77;
  /** RegularExpression Id. */
  int ASSIGN = 78;
  /** RegularExpression Id. */
  int GT = 79;
  /** RegularExpression Id. */
  int LT = 80;
  /** RegularExpression Id. */
  int BANG = 81;
  /** RegularExpression Id. */
  int TILDE = 82;
  /** RegularExpression Id. */
  int COLON = 83;
  /** RegularExpression Id. */
  int EQ = 84;
  /** RegularExpression Id. */
  int LE = 85;
  /** RegularExpression Id. */
  int GE = 86;
  /** RegularExpression Id. */
  int NE = 87;
  /** RegularExpression Id. */
  int SC_OR = 88;
  /** RegularExpression Id. */
  int SC_AND = 89;
  /** RegularExpression Id. */
  int INCR = 90;
  /** RegularExpression Id. */
  int DECR = 91;
  /** RegularExpression Id. */
  int PLUS = 92;
  /** RegularExpression Id. */
  int MINUS = 93;
  /** RegularExpression Id. */
  int STAR = 94;
  /** RegularExpression Id. */
  int SLASH = 95;
  /** RegularExpression Id. */
  int BIT_AND = 96;
  /** RegularExpression Id. */
  int BIT_OR = 97;
  /** RegularExpression Id. */
  int XOR = 98;
  /** RegularExpression Id. */
  int REM = 99;
  /** RegularExpression Id. */
  int LSHIFT = 100;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 101;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 102;
  /** RegularExpression Id. */
  int PLUSASSIGN = 103;
  /** RegularExpression Id. */
  int MINUSASSIGN = 104;
  /** RegularExpression Id. */
  int STARASSIGN = 105;
  /** RegularExpression Id. */
  int SLASHASSIGN = 106;
  /** RegularExpression Id. */
  int ANDASSIGN = 107;
  /** RegularExpression Id. */
  int ORASSIGN = 108;
  /** RegularExpression Id. */
  int XORASSIGN = 109;
  /** RegularExpression Id. */
  int REMASSIGN = 110;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 111;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 112;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 113;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"ack\"",
    "\"at\"",
    "\"behavior\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"char\"",
    "\"const\"",
    "\"default\"",
    "\"delay\"",
    "\"double\"",
    "\"enum\"",
    "\"else\"",
    "\"endif\"",
    "\"extends\"",
    "\"false\"",
    "\"float\"",
    "\"for\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"later\"",
    "\"long\"",
    "\"loop\"",
    "\"module\"",
    "\"new\"",
    "\"null\"",
    "\"object\"",
    "\"pass\"",
    "\"parent\"",
    "\"public\"",
    "\"reference\"",
    "\"self\"",
    "\"short\"",
    "\"super\"",
    "\"switch\"",
    "\"token\"",
    "\"true\"",
    "\"waitfor\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"<-\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"?\"",
    "\"@\"",
  };

}
