/* Generated By:JavaCC: Do not edit this line. SalsaParserTreeConstants.java Version 5.0 */
package salsa_lite.compiler;

public interface SalsaParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTMODULEDECLARATION = 1;
  public int JJTNAME = 2;
  public int JJTIMPORTDECLARATION = 3;
  public int JJTINTERFACEDECLARATION = 4;
  public int JJTBEHAVIORDECLARATION = 5;
  public int JJTENUMERATION = 6;
  public int JJTTYPE = 7;
  public int JJTPRIMITIVETYPE = 8;
  public int JJTINTERFACEMESSAGEHANDLERDECLARATION = 9;
  public int JJTMESSAGEHANDLERDECLARATION = 10;
  public int JJTCONSTRUCTORDECLARATION = 11;
  public int JJTFORMALPARAMETERS = 12;
  public int JJTFORMALPARAMETER = 13;
  public int JJTBLOCK = 14;
  public int JJTSTATEMENT = 15;
  public int JJTPASSSTATEMENT = 16;
  public int JJTSTATEMENTEXPRESSION = 17;
  public int JJTFORINIT = 18;
  public int JJTFORSTATEMENT = 19;
  public int JJTWHILESTATEMENT = 20;
  public int JJTIFSTATEMENT = 21;
  public int JJTSWITCHSTATEMENT = 22;
  public int JJTCASESTATEMENT = 23;
  public int JJTDEFAULTSTATEMENT = 24;
  public int JJTLABELSTATEMENT = 25;
  public int JJTBREAKSTATEMENT = 26;
  public int JJTLOCALVARIABLEDECLARATION = 27;
  public int JJTVARIABLEINITIALIZATION = 28;
  public int JJTARRAYINITIALIZATION = 29;
  public int JJTEXPRESSION = 30;
  public int JJTVALUE = 31;
  public int JJTVARIABLENAME = 32;
  public int JJTFIELDACCESS = 33;
  public int JJTMETHODINVOCATION = 34;
  public int JJTMESSAGESEND = 35;
  public int JJTMESSAGEPROPERTY = 36;
  public int JJTARGUMENTS = 37;
  public int JJTALLOCATION = 38;
  public int JJTBINDDECLARATION = 39;
  public int JJTARRAYDIMSANDINITS = 40;
  public int JJTLITERAL = 41;
  public int JJTSELFLITERAL = 42;
  public int JJTPARENTLITERAL = 43;
  public int JJTINTEGERLITERAL = 44;
  public int JJTFLOATINGPOINTLITERAL = 45;
  public int JJTCHARACTERLITERAL = 46;
  public int JJTSTRINGLITERAL = 47;
  public int JJTBOOLEANLITERAL = 48;
  public int JJTNULLLITERAL = 49;
  public int JJTACKNOWLEDGEMENTLITERAL = 50;
  public int JJTASSIGNMENTOPERATOR = 51;
  public int JJTOPERATOR = 52;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "ModuleDeclaration",
    "Name",
    "ImportDeclaration",
    "InterfaceDeclaration",
    "BehaviorDeclaration",
    "Enumeration",
    "Type",
    "PrimitiveType",
    "InterfaceMessageHandlerDeclaration",
    "MessageHandlerDeclaration",
    "ConstructorDeclaration",
    "FormalParameters",
    "FormalParameter",
    "Block",
    "Statement",
    "PassStatement",
    "StatementExpression",
    "ForInit",
    "ForStatement",
    "WhileStatement",
    "IfStatement",
    "SwitchStatement",
    "CaseStatement",
    "DefaultStatement",
    "LabelStatement",
    "BreakStatement",
    "LocalVariableDeclaration",
    "VariableInitialization",
    "ArrayInitialization",
    "Expression",
    "Value",
    "VariableName",
    "FieldAccess",
    "MethodInvocation",
    "MessageSend",
    "MessageProperty",
    "Arguments",
    "Allocation",
    "BindDeclaration",
    "ArrayDimsAndInits",
    "Literal",
    "SelfLiteral",
    "ParentLiteral",
    "IntegerLiteral",
    "FloatingPointLiteral",
    "CharacterLiteral",
    "StringLiteral",
    "BooleanLiteral",
    "NullLiteral",
    "AcknowledgementLiteral",
    "AssignmentOperator",
    "Operator",
  };
}
/* JavaCC - OriginalChecksum=c70fa0b4978c2602ce96b51e0020f666 (do not edit this line) */
