/* Generated By:JavaCC: Do not edit this line. SalsaParserTreeConstants.java Version 5.0 */
package salsa_lite.compiler;

public interface SalsaParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTMODULEDECLARATION = 1;
  public int JJTGENERICTYPE = 2;
  public int JJTGENERICDECLARATION = 3;
  public int JJTNAME = 4;
  public int JJTIMPORTDECLARATION = 5;
  public int JJTINTERFACEDECLARATION = 6;
  public int JJTBEHAVIORDECLARATION = 7;
  public int JJTENUMERATION = 8;
  public int JJTTYPE = 9;
  public int JJTPRIMITIVETYPE = 10;
  public int JJTINTERFACEMESSAGEHANDLERDECLARATION = 11;
  public int JJTMESSAGEHANDLERDECLARATION = 12;
  public int JJTCONSTRUCTORDECLARATION = 13;
  public int JJTFORMALPARAMETERS = 14;
  public int JJTFORMALPARAMETER = 15;
  public int JJTBLOCK = 16;
  public int JJTSTATEMENT = 17;
  public int JJTPASSSTATEMENT = 18;
  public int JJTSTATEMENTEXPRESSION = 19;
  public int JJTFORINIT = 20;
  public int JJTEXTENDEDFOR = 21;
  public int JJTFORSTATEMENT = 22;
  public int JJTWHILESTATEMENT = 23;
  public int JJTIFSTATEMENT = 24;
  public int JJTSYNCHRONIZEDSTATEMENT = 25;
  public int JJTTRYSTATEMENT = 26;
  public int JJTSWITCHSTATEMENT = 27;
  public int JJTCASESTATEMENT = 28;
  public int JJTDEFAULTSTATEMENT = 29;
  public int JJTLABELSTATEMENT = 30;
  public int JJTBREAKSTATEMENT = 31;
  public int JJTLOCALVARIABLEDECLARATION = 32;
  public int JJTVARIABLEINITIALIZATION = 33;
  public int JJTARRAYINITIALIZATION = 34;
  public int JJTEXPRESSION = 35;
  public int JJTVALUE = 36;
  public int JJTVARIABLENAME = 37;
  public int JJTFIELDACCESS = 38;
  public int JJTMETHODINVOCATION = 39;
  public int JJTMESSAGESEND = 40;
  public int JJTMESSAGEPROPERTY = 41;
  public int JJTARGUMENTS = 42;
  public int JJTALLOCATION = 43;
  public int JJTBINDDECLARATION = 44;
  public int JJTARRAYDIMSANDINITS = 45;
  public int JJTLITERAL = 46;
  public int JJTSELFLITERAL = 47;
  public int JJTPARENTLITERAL = 48;
  public int JJTINTEGERLITERAL = 49;
  public int JJTFLOATINGPOINTLITERAL = 50;
  public int JJTCHARACTERLITERAL = 51;
  public int JJTSTRINGLITERAL = 52;
  public int JJTBOOLEANLITERAL = 53;
  public int JJTNULLLITERAL = 54;
  public int JJTACKNOWLEDGEMENTLITERAL = 55;
  public int JJTASSIGNMENTOPERATOR = 56;
  public int JJTOPERATOR = 57;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "ModuleDeclaration",
    "GenericType",
    "GenericDeclaration",
    "Name",
    "ImportDeclaration",
    "InterfaceDeclaration",
    "BehaviorDeclaration",
    "Enumeration",
    "Type",
    "PrimitiveType",
    "InterfaceMessageHandlerDeclaration",
    "MessageHandlerDeclaration",
    "ConstructorDeclaration",
    "FormalParameters",
    "FormalParameter",
    "Block",
    "Statement",
    "PassStatement",
    "StatementExpression",
    "ForInit",
    "ExtendedFor",
    "ForStatement",
    "WhileStatement",
    "IfStatement",
    "SynchronizedStatement",
    "TryStatement",
    "SwitchStatement",
    "CaseStatement",
    "DefaultStatement",
    "LabelStatement",
    "BreakStatement",
    "LocalVariableDeclaration",
    "VariableInitialization",
    "ArrayInitialization",
    "Expression",
    "Value",
    "VariableName",
    "FieldAccess",
    "MethodInvocation",
    "MessageSend",
    "MessageProperty",
    "Arguments",
    "Allocation",
    "BindDeclaration",
    "ArrayDimsAndInits",
    "Literal",
    "SelfLiteral",
    "ParentLiteral",
    "IntegerLiteral",
    "FloatingPointLiteral",
    "CharacterLiteral",
    "StringLiteral",
    "BooleanLiteral",
    "NullLiteral",
    "AcknowledgementLiteral",
    "AssignmentOperator",
    "Operator",
  };
}
/* JavaCC - OriginalChecksum=b14742418d2d2fed6ff237a7fe46e9e8 (do not edit this line) */
